# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_auto_20160221_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='flag',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
